[build]
builder = "nixpacks"

[build.nixpacks]
nixpkgsArchive = "nixpkgs-unstable"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"